name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      run: sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
    - name: make
      run: cd MagikoopaUI && qmake Magikoopa.pro && make
    - uses: actions/upload-artifact@v4
      with:
        name: magikoopa-linux
        path: MagikoopaUI/Magikoopa
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        arch: 'win64_msvc2022_64'
    - name: make
      run: cd MagikoopaUI && qmake Magikoopa.pro && make
    - uses: actions/upload-artifact@v4
      with:
        name: magikoopa-windows
        path: Magikoopa.exe