name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
    - name: make
      run: cd MagikoopaUI && qmake Magikoopa.pro && make
    - uses: actions/upload-artifact@v4
      with:
        name: magikoopa-linux
        path: Magikoopa
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
    - name: make
      run: cd MagikoopaUI && qmake Magikoopa.pro && make
    - uses: actions/upload-artifact@v4
      with:
        name: magikoopa-windows
        path: Magikoopa.exe